runtime: go
env: flex
service: autojoin

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "1.21"

endpoints_api_service:
  name: autojoin-dot-{{PROJECT_ID}}.appspot.com
  rollout_strategy: managed

resources:
  cpu: 2
  memory_gb: 8

network:
  # TODO(soltesz): setup monitoring for production (in mlab-autojoin).
  name: locate
  forwarded_ports:
    - 9090/tcp

liveness_check:
  path: "/v0/live"
  initial_delay_sec: 300

readiness_check:
  path: "/v0/ready"
  app_start_timeout_sec: 300

env_variables:
  PROMETHEUSX_LISTEN_ADDRESS: ':9090' # Must match one of the forwarded_ports above.
  MAXMIND_URL: gs://downloader-{{PROJECT_ID}}/Maxmind/current/GeoLite2-City.tar.gz
  ROUTEVIEW_V4_URL: gs://downloader-{{PROJECT_ID}}/RouteViewIPv4/current/routeview.pfx2as.gz
  REDIS_ADDRESS: {{REDIS_ADDRESS}}
